name: 'yelp_dbt'
version: '1.0'
config-version: 2

profile: 'yelp_dbt'

# Define the folder structure
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  yelp_dbt:
    staging:
      +materialized: view
